#GA Constants
NUMBER_OF_GENERATIONS = 2
POPULATION_SIZE = 3
MUTATION_RATE = 0.8

#MA Constants
MA_MODE = True
LOCAL_SEARCH_STEPS = 3

#POKEMON GA Specific Constants
NO_HELD_ITEM_RATE = 0 #TODO SET THIS TO SUITABLE VALUE
NO_MOVE_RATE = 0 #TODO SET THIS TO SUITABLE VALUE
NO_TEAM_MEMBER_RATE = 0 #TODO SET THIS TO SUITABLE VALUE

#Pokebase Constants
MIN_FORMID = 1
MAX_FORMID = 802
MIN_ITEMID = 1
MAX_ITEMID = 918
MIN_LEVEL = 1
MAX_LEVEL = 100
MIN_HAPPINESS = 0
MAX_HAPPINESS = 255
MIN_NATUREID = 1
MAX_NATUREID = 25
NUMBER_OF_STATS = 6
MIN_IV = 0
MAX_IV = 31
MAX_EV_TOTAL = 510
MIN_EV = 0
MAX_EV = 252
NUMBER_OF_MOVES = 4
