#TODO: ADD IN MIN CONSTANTS TO MAKE RANGES EASIER

#GA Constants
NUMBER_OF_GENERATIONS = 50
POPULATION_SIZE = 10
MUTATION_RATE = 0.1

#POKEMON GA Specific Constants
NO_HELD_ITEM_RATE = 0 #TODO SET THIS TO SUITABLE VALUE
NO_MOVE_RATE = 0 #TODO SET THIS TO SUITABLE VALUE
NO_TEAM_MEMBER_RATE = 0 #TODO SET THIS TO SUITABLE VALUE

#Pokebase Constants
MAX_FORMID = 802
MAX_ITEMID = 918
MAX_LEVEL = 100
MAX_HAPPINESS = 255
MAX_NATUREID = 25
MAX_IV = 31
MAX_EV_TOTAL = 510
MAX_EV = 252
